version: "3.8"

services:
  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: pipsap-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pipsap-network

  # Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    container_name: pipsap-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - pipsap-network

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    container_name: pipsap-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - pipsap-network

volumes:
  redis_data:
  mysql_data:

networks:
  pipsap-network:
    driver: bridge
