server:
  port: -1 # Disable HTTP server to avoid port conflicts

spring:
  application:
    name: stock-price-service

  kafka:
    bootstrap-servers: localhost:9092 # Kafka container/service
    consumer:
      group-id: stock-price-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

grpc:
  server:
    port: 9090
    address: localhost
    enable-reflection: true

logging:
  level:
    root: INFO
    org.apache.kafka: WARN
    com.pipsap.stockpriceservice: DEBUG
    org.springframework.grpc: DEBUG
    io.grpc: DEBUG
